# Generated by Django 5.2.5 on 2025-10-04 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'App Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android'), ('Windows', 'Windows'), ('macOS', 'macOS'), ('Web', 'Web')], max_length=20)),
                ('storage_size_mb', models.IntegerField(default=0)),
                ('last_used_date', models.DateField(blank=True, null=True)),
                ('usefulness_rating', models.CharField(choices=[('useful', 'Useful'), ('maybe_useful', 'Maybe Useful'), ('useless', 'Useless')], default='useful', max_length=20)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_apps', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='apps_manager.appcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
