# Generated by Django 5.2.5 on 2025-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android'), ('Windows', 'Windows'), ('macOS', 'macOS'), ('Web', 'Web')], max_length=30),
        ),
        migrations.AlterField(
            model_name='app',
            name='usefulness_rating',
            field=models.CharField(choices=[('useful', 'Useful'), ('maybe_useful', 'Maybe Useful'), ('useless', 'Useless'), ('okay', 'Okay')], default='useful', max_length=20),
        ),
    ]
