# Generated by Django 5.2.5 on 2025-10-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
